mutation {
  backup(
    input: {
      destination: ""
      accessKey: ""
      secretKey: ""
      sessionToken: ""
      anonymous: false
      forceFull: false
    }
  ) {
    response {
      code
      message
    }
    taskId
  }
}
